### ISSUE TITLE
Homebridge fails to load with plugin running

### ISSUE THREAD

**Issue by ciscosurplus** [tonesto7/homebridge-smartthings#171]
re-added home bridge-smarthings last night, was all working fine last night, crashed overnight as I was running manual on Pi3 to test. Today it won't load with the following error;

If I remove smarthings from my config.json its running fine, weird how it worked last night just fine. Could it one device causing issues? 

[3/30/2017, 8:23:22 AM] [SmartThings] Initializing SmartThings platform...
[3/30/2017, 8:23:22 AM] [SmartThings] Fetching Smart Things devices.
[3/30/2017, 8:23:22 AM] Loading 2 accessories...
[3/30/2017, 8:23:22 AM] [Living Room Speakers] Initializing Sonos accessory...
[3/30/2017, 8:23:22 AM] [Kitchen Speakers] Initializing Sonos accessory...
[3/30/2017, 8:23:23 AM] [Kitchen Speakers] Found a playable coordinator device at 192.168.1.212 in zone 'Kitchen' for accessory 'Kitchen Speakers' in accessory room 'Kitchen'
[3/30/2017, 8:23:23 AM] [Living Room Speakers] Found a playable coordinator device at 192.168.1.237 in zone 'Living Room' for accessory 'Living Room Speakers' in accessory room 'Living Room'
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group lights, Name Bedroom, ID 06050d01-88ea-4f7a-81ef-f29b7d4f002b
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group lights, Name Fynleys room, ID c0be5105-9a5b-426a-9d27-cd0b3bd80f7b
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group switch, Name Hallway Lamp, ID 4e9be188-aea8-47ea-9813-eaea300edc7f
[3/30/2017, 8:23:24 AM] [SmartThings] Device Skipped - Group unknown, Name Hue Bridge (2A30AA), ID 489fdb2f-124b-4d27-9313-1f46fc9f3e71, JSON: {"name":"Hue Bridge (2A30AA)","deviceid":"489fdb2f-124b-4d27-9313-1f46fc9f3e71","capabilities":{"Refresh":1,"Health Check":1,"Bridge":1},"commands":{"refresh":[],"ping":[]},"attributes":{"checkInterval":null,"networkAddress":"192.168.1.222:80","status":"Online","serialNumber":"2A30AA","info":"If removed, all Hue lights will be removed as well"}}
[3/30/2017, 8:23:24 AM] [SmartThings] Device Skipped - Group unknown, Name Kitchen, ID 8b96e5f2-ba7a-44cf-8225-4a227f93d02d, JSON: {"name":"Kitchen","deviceid":"8b96e5f2-ba7a-44cf-8225-4a227f93d02d","capabilities":{"Refresh":1,"Media Controller":1},"commands":{"refresh":[],"startActivity":["STRING"],"getAllActivities":[],"getCurrentActivity":[],"activityoff":[],"alloff":[]},"attributes":{"activities":"[{\"id\":\"11183328\",\"name\":\"Kitchen Sky TV\",\"type\":1},{\"id\":\"19911754\",\"name\":\"Kitchen Fire TV\",\"type\":13},{\"id\":\"11183392\",\"name\":\"Kitchen APPLE TV\",\"type\":9},{\"id\":\"11361796\",\"name\":\"Kitchen DVD\",\"type\":2},{\"id\":\"off\",\"name\":\"Activity OFF\",\"type\":\"0\"}]","currentActivity":"--"}}
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group switch, Name Kitchen Apple TV, ID e1476105-4b50-4f81-9f16-27e2a5785c43
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group switch, Name Kitchen DVD, ID 1f2f4b12-c4da-47f0-9ad4-f9176cadb888
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group switch, Name Kitchen Fire TV, ID 91f9815a-fe67-4d30-bb8b-e3f1d9b96f32
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group switch, Name Kitchen Sonos, ID 254f871e-1c7b-4523-bf45-92030ae5c481
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group switch, Name Kitchen Sky TV, ID aa5e4c55-a1f2-4ad9-be61-1635276e8075
[3/30/2017, 8:23:24 AM] [SmartThings] Device Skipped - Group unknown, Name Living Room, ID 43585592-de35-4a6d-bdfc-3c75318f6f6b, JSON: {"name":"Living Room","deviceid":"43585592-de35-4a6d-bdfc-3c75318f6f6b","capabilities":{"Refresh":1,"Media Controller":1},"commands":{"refresh":[],"startActivity":["STRING"],"getAllActivities":[],"getCurrentActivity":[],"activityoff":[],"alloff":[]},"attributes":{"activities":"[{\"id\":\"20032656\",\"name\":\"Living Room Kodi\",\"type\":12},{\"id\":\"20032643\",\"name\":\"Living Room Apple TV\",\"type\":9},{\"id\":\"20030310\",\"name\":\"Living Room TV\",\"type\":1},{\"id\":\"20032639\",\"name\":\"Living Room DVD\",\"type\":2},{\"id\":\"off\",\"name\":\"Activity OFF\",\"type\":\"0\"}]","currentActivity":"--"}}
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group lights, Name Living Room 1, ID fd3582c9-b3ec-49e9-bb69-0072085f5184
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group lights, Name Living Room 2, ID 1a94ee4f-0124-43e3-b77b-4d984d952144
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group switch, Name Living Room Apple TV, ID 3ed4eaeb-32b2-4f2b-bb39-d33ef5093991
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group switch, Name Living Room DVD, ID c0391a78-cb0e-4932-be66-1ee13d9b06e7
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group switch, Name Living Room Kodi, ID 651d73a1-5827-4424-b9ef-e21e233ac198
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group lights, Name Living Room Lamp, ID 47d9d69f-b2e4-4b57-addf-a94498b3d171
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group switch, Name Living Room Sky TV, ID b1d96956-815a-4834-bc2c-748b4ab9f59c
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group switch, Name Living Room Sonos, ID ef753d1d-b474-494b-8094-a3a33c64859a
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group switch, Name Living Room Sonos 1, ID 25c89cf8-3271-4e21-9729-a40936cd67b2
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group switch, Name Living Room Sonos 2, ID ca7051c1-4205-4cad-8b33-f66488f69103
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group switch, Name Living Room Sonos Sub, ID 2cfad633-6344-431c-8587-28152beebf0a
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group lights, Name Maiyas Room, ID 44cdb838-eb27-447a-9788-2adddc89348b
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group sensor, Name Motion Sensor, ID 166a3918-51a7-4d19-9925-2a7411ef9794
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group sensor, Name Multipurpose Sensor, ID 1c7f91a8-7dc6-45a8-adf1-92ce29aa9230
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group switch, Name Outside Lights, ID 42056d4e-ce73-4960-a924-cc6c2acce979
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group sensor, Name Water Leak Sensor, ID 512d1d24-7a9c-4cad-8ecf-269dd9218f44
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group switch, Name fan, ID 1388d041-ace5-45d1-81e3-eaeebe3cec49
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group sensor, Name Gemma Sensor, ID 9cce8b78-da35-4a8e-8041-9bec43cdca11
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group sensor, Name Graham Sensor, ID f4c1a6e5-35e0-47ba-805b-439bb867bff4
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group sensor, Name Graham's iPhone, ID 9dbac94f-ff24-4dc0-be2c-5d04b6bd4fad
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group lights, Name Bedroom 5 lights, ID 99c99b41-9fb8-4c14-890a-645d11ff8071
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group lights, Name Office Lights, ID f6d30dc5-1b11-4e67-b350-0e16ebefe4db
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group switch, Name Plant Lights, ID bee69d8d-023b-43e2-b1ab-b2ec3889f0a6
[3/30/2017, 8:23:24 AM] [SmartThings] Device Added - Group lights, Name Studio Lights, ID 9c614f70-44b1-424f-a4e3-0615919083f6
[3/30/2017, 8:23:24 AM] [SmartThings] Unknown Capabilities: ["Health Check","Light","Outlet","Bridge","Media Controller","Music Player","Audio Notification","Water Sensor","Tone","Signal Strength"]
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Bedroom'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Fynleys room'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Hallway Lamp'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Kitchen Apple TV'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Kitchen DVD'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Kitchen Fire TV'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Kitchen Sonos'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Kitchen Sky TV'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Living Room 1'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Living Room 2'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Living Room Apple TV'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Living Room DVD'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Living Room Kodi'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Living Room Lamp'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Living Room Sky TV'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Living Room Sonos'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Living Room Sonos 1'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Living Room Sonos 2'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Living Room Sonos Sub'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Maiyas Room'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Motion Sensor'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Multipurpose Sensor'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Outside Lights'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Water Leak Sensor'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'fan'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Gemma Sensor'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Graham Sensor'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Graham's iPhone'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Bedroom 5 lights'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Office Lights'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Plant Lights'...
[3/30/2017, 8:23:24 AM] [SmartThings] Initializing platform accessory 'Studio Lights'...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8000
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1236:14)
    at listen (net.js:1272:10)
    at Server.listen (net.js:1368:5)
    at smartthings_SetupHTTPServer (/usr/local/lib/node_modules/homebridge-smartthings/index.js:203:9)
    at /usr/local/lib/node_modules/homebridge-smartthings/index.js:138:5
    at /usr/local/lib/node_modules/homebridge-smartthings/index.js:98:5
    at /usr/local/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:94:29
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:45:29)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickCallback (node.js:351:17)

**Comment by pdlove** [comment]
On the error you are getting now, there is another instance of home bridge that still has the plugin's receive port blocked. Reboot the Pi and it should work. Do you know what error you got when it crashed before you restarted it and got this?
