### ISSUE TITLE
Can't Start Homebridge

### ISSUE THREAD

**Issue by strangedesign13** [tonesto7/homebridge-smartthings#193]
I have been trying to get homebridge working with my smart things and keep running into the follow problem. When I start homebridge with no config.json file it starts up fine. As soon as I add in a config.json I get:

[7/1/2017, 10:51:36 AM] Loaded plugin: homebridge-smartthings
[7/1/2017, 10:51:36 AM] Registering platform 'homebridge-smartthings.SmartThings'
[7/1/2017, 10:51:36 AM] ---
/usr/local/lib/node_modules/homebridge/lib/server.js:202
  var username = config.bridge.username;
                              ^

TypeError: Cannot read property 'username' of undefined
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:202:31)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:52:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)

Any ideas what I could be doing wrong?

**Comment by strangedesign13** [comment]
Well I fixed it myself after finding https://github.com/nfarina/homebridge/issues/1189

I didn't have the base confi.json for homebridge, only the smartthings plartform piece.
