### ISSUE TITLE
Errors adding Orsam Lightify light strips

### ISSUE THREAD

**Issue by pcamp96** [tonesto7/homebridge-smartthings#236]
I have two lights checked within the config (ORSAM Lightify Flex RGBW), but when I try to run Homebridge, it throws the following error:
[2018-1-30 14:59:01] Loaded plugin: homebridge-smartthings
[2018-1-30 14:59:01] Registering platform 'homebridge-smartthings.SmartThings'
[2018-1-30 14:59:01] ---
[2018-1-30 14:59:02] Loaded plugin: homebridge-synology
[2018-1-30 14:59:02] Registering accessory 'homebridge-synology.Synology'
[2018-1-30 14:59:02] ---
[2018-1-30 14:59:02] Loaded config.json with 1 accessories and 1 platforms.
[2018-1-30 14:59:02] ---
[2018-1-30 14:59:02] Loading 1 platforms...
[2018-1-30 14:59:02] [SmartThings] Initializing SmartThings platform...
[2018-1-30 14:59:02] [SmartThings] Fetching Smart Things devices.
[2018-1-30 14:59:02] Loading 1 accessories...
/usr/lib/node_modules/homebridge/lib/api.js:64
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory '' was not registered by any plugin.
    at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:264:42)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:86:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

Any thoughts here? When I go to check the device results within the SmartApp they show up perfectly fine.

**Comment by jelockwood** [comment]
Since Osram Lightify devices can be added to a Philips Hue Bridge and since the Philips Hue Bridge is a native HomeKit capable system is there a need to use HomeBridge in this case?

See https://www.any-lamp.com/blog/Breaking-News-Philips-HUE-bridge-is-compatible-with-Osram-lamps

However there is one wrinkle - see https://developers.meethue.com/comment/1725#comment-1725
You can apparently re-flash the lamps from US to EU standard to make them compatible - see https://community.smartthings.com/t/osram-lightify-bulbs-connect-to-hue-or-smartthings/79767/4

You will still be able to use the Philips Hue and the Osram lamps with Smartthings as well.
