### ISSUE TITLE
Post 2.3.5 update Unable to load plugin/start HOOBS servic

### ISSUE THREAD

**Issue by darth-monkey** [tonesto7/homebridge-smartthings#394]
Hello! 

I seem to be running into an issue after upgrading to 2.3.5 Hoobs plugin (Smart things app is still at 2.3.3 as the latest available):

```Dec 30 10:01:06 hoobs hoobs[1108]: Error loading platform requested in your config.json at position 3
Dec 30 10:01:06 hoobs hoobs[1108]: Error: The requested platform 'SmartThings-v2' was not registered by any plugin.
Dec 30 10:01:06 hoobs hoobs[1108]:     at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/pluginManager.js:152:23)
Dec 30 10:01:06 hoobs hoobs[1108]:     at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:334:45
Dec 30 10:01:06 hoobs hoobs[1108]:     at Array.forEach (<anonymous>)
Dec 30 10:01:06 hoobs hoobs[1108]:     at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:320:31)
Dec 30 10:01:06 hoobs hoobs[1108]:     at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:152:35)
Dec 30 10:01:06 hoobs hoobs[1108]:     at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
Dec 30 10:01:06 hoobs hoobs[1108]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
Dec 30 10:01:06 hoobs hoobs[1108]: Got SIGTERM, shutting down Bridge...```

**Comment by rjbh002** [comment]
I'm also having the same issue.  

Error: The requested platform 'SmartThings-v2' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/pluginManager.js:152:23)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:334:45
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:320:31)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:152:35)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by hackert66** [comment]
I´m also having the same issue.

Error: The requested platform 'SmartThings-v2' was not registered by any plugin.
at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/pluginManager.js:152:23)                                      at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:334:45
at Array.forEach (<anonymous>)
at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:320:31)
at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:152:35)
at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
at processTicksAndRejections (internal/process/task_queues.js:97:5)

Can you help me ?

**Comment by ASDylag** [comment]
I´m also having the same issue after upgrading to 2.3.5 Hoobs plugin. 

Error loading platform requested in your config.json at position 7
30/12/2020, 22:20:39 Error: The requested platform 'SmartThings-v2' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/src/hoobs/node_modules/homebridge/lib/pluginManager.js:152:23)
    at /usr/src/hoobs/bridge/server.js:334:45
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/src/hoobs/bridge/server.js:320:31)
    at Server.start (/usr/src/hoobs/bridge/server.js:152:35)
    at /usr/src/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

Please help?

**Comment by darth-monkey** [comment]
> I´m also having the same issue after upgrading to 2.3.5 Hoobs plugin.
> HOOBS service won't start after update.
> 
> Error loading platform requested in your config.json at position 7
> 30/12/2020, 22:20:39 Error: The requested platform 'SmartThings-v2' was not registered by any plugin.
> at PluginManager.getPluginForPlatform (/usr/src/hoobs/node_modules/homebridge/lib/pluginManager.js:152:23)
> at /usr/src/hoobs/bridge/server.js:334:45
> at Array.forEach ()
> at Server.loadPlatforms (/usr/src/hoobs/bridge/server.js:320:31)
> at Server.start (/usr/src/hoobs/bridge/server.js:152:35)
> at /usr/src/hoobs/bridge/cli.js:94:16
> at processTicksAndRejections (internal/process/task_queues.js:93:5)
> 
> Please help?
> 
> Update: after removing **SmartThings V2 2.3.5 published 12/29/2020** plugin and installing **SmartThings 2.3.8 published 8/19/2020** Hoobs is back and working.

Thank you for the workaround! The trick is to have both the August plugin (non-V2) and the V2 plugin. The HOOBS service can then start.

**Comment by VAJeff** [comment]
I have the same issue, I did the workaround darth-monkey suggested, and HOOBS service started working right away!

**Comment by adavison007** [comment]
> > I´m also having the same issue after upgrading to 2.3.5 Hoobs plugin.
> > HOOBS service won't start after update.
> > Error loading platform requested in your config.json at position 7
> > 30/12/2020, 22:20:39 Error: The requested platform 'SmartThings-v2' was not registered by any plugin.
> > at PluginManager.getPluginForPlatform (/usr/src/hoobs/node_modules/homebridge/lib/pluginManager.js:152:23)
> > at /usr/src/hoobs/bridge/server.js:334:45
> > at Array.forEach ()
> > at Server.loadPlatforms (/usr/src/hoobs/bridge/server.js:320:31)
> > at Server.start (/usr/src/hoobs/bridge/server.js:152:35)
> > at /usr/src/hoobs/bridge/cli.js:94:16
> > at processTicksAndRejections (internal/process/task_queues.js:93:5)
> > Please help?
> > Update: after removing **SmartThings V2 2.3.5 published 12/29/2020** plugin and installing **SmartThings 2.3.8 published 8/19/2020** Hoobs is back and working.
> 
> Thank you for the workaround! The trick is to have both the August plugin (non-V2) and the V2 plugin. The HOOBS service can then start.

PLEASE CAN YOU CONFIRM @darth-monkey @VAJeff  ? Are you saying we need both homebridge-smarthings and home bridge-smarthings-v2 installed at the same time, I'm confused at which one to use (I'm on hoobs)

**Comment by VAJeff** [comment]
I am on HOOBS as well, and when I updated the the Dec 29th Update, HOOBS Service would not start.  I deleted all (including the Samsung SmartApp info.  Deleted my other plugin (Ring), reset HOOBS to new, etc.  HOOBS worked fine with Ring, but as soon as I installed SmartThings V2, HOOBS Services would not start.

After a few hours troubleshooting, I went to Google, and the support site.  I saw @darth-monkey’s work around.  Went back in and installed V! (actually has no indication ov version), and all worked as soon as I installed it (while leaving V@ configured as it should be) installed as well.

**Comment by adavison007** [comment]
> I am on HOOBS as well, and when I updated the the Dec 29th Update, HOOBS Service would not start. I deleted all (including the Samsung SmartApp info. Deleted my other plugin (Ring), reset HOOBS to new, etc. HOOBS worked fine with Ring, but as soon as I installed SmartThings V2, HOOBS Services would not start. After a few hours troubleshooting, I went to Google, and the support site. I saw @darth-monkey’s work around. Went back in and installed V! (actually has no indication ov version), and all worked as soon as I installed it (while leaving V@ configured as it should be) installed as well.
> […](#)

Thanks, so you are running both plugins?

**Comment by VAJeff** [comment]
Yes.  I installed V2, and set everything up.  I then installed V1, and Services started right up.  I did not have to do any configuration after installing V1.

**Comment by adavison007** [comment]
Thanks, just done the same, then took a deep breath and deleted the old plugin and all still works fine! :) thank you.

**Comment by ASDylag** [comment]
**I can only add that SmartThings V2**

This Plugin is now DEPRECATED…

I've acquired the original homebridge-smartthings repo and npm package from @pdlove and i've updated the code to the latest v2.x Please use the new version here: https://github.com/tonesto7/homebridge-smartthings

**Comment by VAJeff** [comment]
I am afraid to go in and delete any plugins at this point.  I have two versions installed on HOOBS.  When it was just the V2 version, HOOBS services would always crash.  It was 



When I go to HOOBS config I see both as “V2”, and they are configured identical.  I only configured the 1st V2 (2.3.5 published 12/29/202) and that was the one that kept crashing HOOBS Services.  I then just installed the other (2.3.8 published 8/19/2020), and HOOBS Services instantly started working.

**Comment by ASDylag** [comment]
Open Hoobs plugin SmartThings V2 go to Details and you see:

_This Plugin is now DEPRECATED…
I've acquired the original homebridge-smartthings repo and npm package from @pdlove and i've updated the code to the latest v2.x Please use the new version here: https://github.com/tonesto7/homebridge-smartthings_

The SmartThings (non-V2) is now V2 2.3.8

**Comment by darth-monkey** [comment]
> Open Hoobs plugin SmartThings V2 go to Details and you see:
> 
> _This Plugin is now DEPRECATED… I've acquired the original homebridge-smartthings repo and npm package from @pdlove and i've updated the code to the latest v2.x Please use the new version here: https://github.com/tonesto7/homebridge-smartthings_
> 
> The SmartThings (non-V2) is now V2 2.3.8
> **SmartThings V2 is DEPRECATED**

Hi ASDylag,

I am a bit confused. Within HOOBS, the 2.3.8 plugin has no settings from within UI, how is the connection made to a user's SmartThings home? If I delete the 2.3.5 (V2) plugin, then I cannot control any devices.

**Comment by adavison007** [comment]
> > Open Hoobs plugin SmartThings V2 go to Details and you see:
> > _This Plugin is now DEPRECATED… I've acquired the original homebridge-smartthings repo and npm package from @pdlove and i've updated the code to the latest v2.x Please use the new version here: https://github.com/tonesto7/homebridge-smartthings_
> > The SmartThings (non-V2) is now V2 2.3.8
> > **SmartThings V2 is DEPRECATED**
> 
> Hi ASDylag,
> 
> I am a bit confused. Within HOOBS, the 2.3.8 plugin has no settings from within UI, how is the connection made to a user's SmartThings home? If I delete the 2.3.5 (V2) plugin, then I cannot control any devices.

Hi @darth-monkey I was confused last night, but worked it out.... so homebridge-smartthings-V2 should no longer be used, he has moved the code to homebridge-smartthings.. forget the code versions are different, relevant! install the new plugin (homebridge-smartthings), reboot your PI then once installed and rebooted remove the old plugin (homebridge-smartthings-V2) both plugins are V2...... doing it this way will not remove or change any devices you have already, they both connect to the same smart app.... hope this makes sense, trust me, I took a leap of faith and if you follow this process it will work... Just do not remove the old plugin before the new one is up and running.

**Comment by ASDylag** [comment]
> > > Open Hoobs plugin SmartThings V2 go to Details and you see:
> > > _This Plugin is now DEPRECATED… I've acquired the original homebridge-smartthings repo and npm package from @pdlove and i've updated the code to the latest v2.x Please use the new version here: https://github.com/tonesto7/homebridge-smartthings_
> > > The SmartThings (non-V2) is now V2 2.3.8
> > > **SmartThings V2 is DEPRECATED**
> > 
> > 
> > Hi ASDylag,
> > I am a bit confused. Within HOOBS, the 2.3.8 plugin has no settings from within UI, how is the connection made to a user's SmartThings home? If I delete the 2.3.5 (V2) plugin, then I cannot control any devices.
> 
> Hi @darth-monkey I was confused last night, but worked it out.... so homebridge-smartthings-V2 should no longer be used, he has moved the code to homebridge-smartthings.. forget the code versions are different, irrelevant! install the new plugin (homebridge-smartthings), reboot your PI then once installed and rebooted remove the old plugin (homebridge-smartthings-V2) both plugins are V2...... doing it this way will not remove or change any devices you have already, they both connect to the same smart app.... hope this makes sense, trust me, I took a leap of faith and if you follow this process it will work... Just do not remove the old plugin before the new one is up and running. p.s. they use the same config from the JSON, so no need to do anything with that!

homebridge-smartthings-V2 is no longer available through Hoobs Search only homebridge-smartthings

**Comment by adavison007** [comment]
> > > > Open Hoobs plugin SmartThings V2 go to Details and you see:
> > > > _This Plugin is now DEPRECATED… I've acquired the original homebridge-smartthings repo and npm package from @pdlove and i've updated the code to the latest v2.x Please use the new version here: https://github.com/tonesto7/homebridge-smartthings_
> > > > The SmartThings (non-V2) is now V2 2.3.8
> > > > **SmartThings V2 is DEPRECATED**
> > > 
> > > 
> > > Hi ASDylag,
> > > I am a bit confused. Within HOOBS, the 2.3.8 plugin has no settings from within UI, how is the connection made to a user's SmartThings home? If I delete the 2.3.5 (V2) plugin, then I cannot control any devices.
> > 
> > 
> > Hi @darth-monkey I was confused last night, but worked it out.... so homebridge-smartthings-V2 should no longer be used, he has moved the code to homebridge-smartthings.. forget the code versions are different, irrelevant! install the new plugin (homebridge-smartthings), reboot your PI then once installed and rebooted remove the old plugin (homebridge-smartthings-V2) both plugins are V2...... doing it this way will not remove or change any devices you have already, they both connect to the same smart app.... hope this makes sense, trust me, I took a leap of faith and if you follow this process it will work... Just do not remove the old plugin before the new one is up and running. p.s. they use the same config from the JSON, so no need to do anything with that!
> 
> homebridge-smartthings-V2 is no longer available through Hoobs Search only homebridge-smartthings

Yep, they removed it last night after I advised it was depreciated

**Comment by darth-monkey** [comment]
Thank you everyone for your help and clarification. Rebooting and uninstalling does in fact work. I now have a full config page for the 2.3.8 plugin version!

**Comment by VAJeff** [comment]
I did a backup, then removed the “V2” version leaving only smartthings plugin.  All works fine.

Thanks,

Jeff

**Comment by tarunprakashsingh** [comment]
guys lil help needed... so i install smartthings on hoobs and leave the SmartThings V2 installed? then after everything is installed remove SmartThings V2? this is move everything SmartThings V2 to new SmartThings? 
please help me understand, i am new to hoobs.

**Comment by adavison007** [comment]
Do you have any smarting plugins already installed? If so which one?

**Comment by tarunprakashsingh** [comment]
yes i have door locks and garage openers.

**Comment by adavison007** [comment]
> yes i have door locks and garage openers.

Ok, to help i need to know WHICH PLUGIN is the one you currently have installed if any for smartthings?

**Comment by tarunprakashsingh** [comment]
this is the one:
Smartthings V2
2.3.5 • Published December 29th, 2020
This Plugin is now DEPRECATED…
I've acquired the original homebridge-smartthings repo and npm package from @pdlove and i've updated the code to the latest v2.x
Please use the new version here: https://github.com/tonesto7/homebridge-smartthings

**Comment by tarunprakashsingh** [comment]
any help? @adavison007 
thanks

**Comment by adavison007** [comment]
> any help? @adavison007
> thanks

@tarunprakashsingh OK, so keep everything as it is, do a back up of your system or at min keep a copy of your JSON config... 

Then install this plugin homebridge-smartthings (forget dates and versions), you will now have two smart things pluggin, but only one JSON input for smart things, do not edit the JSON.

Then Reboot the system, wait for it to completely load..... startthings should all now work.... 

Then go to the plugins section and Delete / Remove the original plugin on, the one the ends in V2.... do a restart and everything will work.

hope this makes sense.

It really is as simple as installing the other plugin and then removing the old plugin v2 

The reason for all the differences in code and dates is simply that the coder wanted to have the better plugin name.
