### ISSUE TITLE
(BUG) {stop homebridge no devices found} 

### ISSUE THREAD

**Issue by treforparr** [tonesto7/homebridge-smartthings#395]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [X ] The SmartApp and Device Handler are using the latest code available.
-  [ X] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?:
-  Mobile App Version(Not required):
-  SmartApp Version:
-  Device Handler Version:
-  Homebridge Version:
-  NodeJS Version:

## Expected Behavior
**Tell us what you think should be happening**

## Current Behavior
**What happens instead of the expected behavior?**

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the bug

Needs urgent fixing shop in down-home bridge completely not up-to-date with Home bridge software update resuppository  I'm dyslexic so it's really hard to fill out a form

**Comment by tonesto7** [comment]
There is nothing wrong with plug-in.  You need to follow the instructions carefully and make sure to complete the plug-in configuration.

**Comment by ballakers** [comment]
There is multiple people having issues - revert back to previous version or the non V2 version and all the issues go away.  There is about 4 or 5 of us with HOOBS and the update crashes bridge service.  I'm sure it could be because of a combination of things or other plugins but for sure is causing issues for a lot of people.  Didn't change anything but the update to this plugin.

Log from HOOBS 3.3.1 on node 14.15.1 

/2020, 9:32:33 AM Error loading platform requested in your config.json at position 6
12/30/2020, 9:32:33 AM Error: The requested platform 'SmartThings-v2' was not registered by any plugin.
at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/pluginManager.js:152:23)
at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:334:45
at Array.forEach (<anonymous>)
at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:320:31)
at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:152:35)
at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
at processTicksAndRejections (internal/process/task_queues.js:93:5)
12/30/2020, 9:32:33 AM Got SIGTERM, shutting down Bridge...

**Comment by treforparr** [comment]
There is definite something wrong with your plug-in I know you're saying there isn't and you're saying it's working on your side but several people have reported it not working on a forum  Hoobs./Homebridge the old version works perfectly fine I have manage to get it working by revolting back to the old version in the app homebridge manager 
02/01/2021, 3:31:24 am Error loading platform requested in your config.json at position 5
02/01/2021, 3:31:27 am Error: The requested platform 'SmartThings-v2' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/pluginManager.js:152:23)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:334:45
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:320:31)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:152:35)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5) 
Copied the login and it looks exactly the same several people are reporting it

**Comment by keithkorg** [comment]
this is definitely not working on hoops I have instate this clean two times and its the same issue. appreciate your work on this.

**Comment by bjornand1** [comment]
Hi, I see these problem descriptions, but wonder if these are limited to HOOBS? My Homebridge instantation on Synology Docker shows update to 2.3.8 available, but I am afraid to pull the trigger.

**Comment by guyank** [comment]
I'm having this problem too.  It has worked for months until yesterday:

[1/10/2021, 09:24:34] Error: The requested platform 'SmartThings-v2' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/lib/node_modules/homebridge/src/server.ts:387:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)

**Comment by dcfurst** [comment]
This happened to me too.  Same error when I upgraded to 2.3.5.  I fixed it by uninstalling homebridge-smartthings-v2 and installing homebridge-smartthings.

Now I am current at v2.3.8 and it works.
