### ISSUE TITLE
(BUG) 2.3.5 

### ISSUE THREAD

**Issue by intouchnow** [tonesto7/homebridge-smartthings#398]
updated hoobs to 2.3.5 and now this....can uninstall or rollback

any suggestions would be appreciated 

Error: The requested platform 'SmartThings-v2' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/pluginManager.js:152:23)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:334:45
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:320:31)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:152:35)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by intouchnow** [comment]
Finally got it resolved by installing V1 2.3.8 and then it let me uninstall 2.3.5

**Comment by cedstrom** [comment]
Dupe of #317
