### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-smartthings-v2

### ISSUE THREAD

**Issue by gradyhouston** [tonesto7/homebridge-smartthings#407]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [ x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [ x] The SmartApp and Device Handler are using the latest code available.
-  [ x] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?: 0
-  Mobile App Version(Not required):
-  SmartApp Version: 2.3.3
-  Device Handler Version: 
-  Homebridge Version: 1.1.7 (but I've also tried 1.2.5)
-  NodeJS Version: 12.20.1

## Expected Behavior
Homebridge should be starting up

## Current Behavior
Homebridge is not starting up

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

```
[1/25/2021, 00:30:16] ERROR LOADING PLUGIN homebridge-smartthings-v2:
[1/25/2021, 00:30:17] Error: Cannot find module '/usr/lib/node_modules/homebridge-smartthings-v2/index.js'
Require stack:
- /usr/lib/node_modules/homebridge/lib/plugin.js
- /usr/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/lib/node_modules/homebridge/lib/api.js
- /usr/lib/node_modules/homebridge/lib/server.js
- /usr/lib/node_modules/homebridge/lib/cli.js
- /usr/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Plugin.load (/usr/lib/node_modules/homebridge/src/plugin.ts:181:27)
    at /usr/lib/node_modules/homebridge/src/pluginManager.ts:120:16
    at Map.forEach (<anonymous>)
    at PluginManager.initializeInstalledPlugins (/usr/lib/node_modules/homebridge/src/pluginManager.ts:118:18)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:148:24)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
```

## Context
I've looked through every issue here already. Nothing I've seen resolves this.

I get the above in my logs. I've tried uninstalling homebridge-smartthings-v2, I've tried installing both versions that are searchable in Homebridge, I've tried uninstalling the new version (2.3.8), etc. I'm not sure how to install or get rid of the file it's looking for (index.js). I've completely disassociated my Github from the IDE and re-associated it. I've completely started fresh and deleted the apps from the Smartthings app, deleted the repo from the IDE and started over from scratch following this link: https://thingsthataresmart.wiki/index.php?title=Community_Installer_(Free_Marketplace)#Installation

My Homebridge currently won't start due to this error.

---
Please include a copy of any relevant log output to assist in tracking down the bug:

See above.

**Comment by gradyhouston** [comment]
https://github.com/tonesto7/homebridge-smartthings/issues/354

I'm already on 2.3.8, so the resolution here ^ does not resolve it for me, for some reason? I'm also unsure why it's still looking for "v2".

**Comment by gradyhouston** [comment]
Wow, I think...this error was a red herring. I was also getting a duplicate UUID error that was buried under other log output. Once I resolved that, this issue stopped? Not sure if coincidence, magic, or a direct fix.
