### ISSUE TITLE
Error: Cannot find module '/usr/local/lib/node_modules/homebridge-smartthings-v2/index.js'

### ISSUE THREAD

**Issue by BUMPRW** [tonesto7/homebridge-smartthings#431]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x ] The SmartApp and Device Handler are using the latest code available.
-  [x ] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
-  How many devices are detected?:
-  Mobile App Version(Not required):
-  SmartApp Version:
-  Device Handler Version:
-  Homebridge Version:
-  NodeJS Version:

## Expected Behavior
**Tell us what you think should be happening**

## Current Behavior
**What happens instead of the expected behavior?**

## Steps to Reproduce (for bugs)
**Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant**

1.
2.
3.
4.

## Context
**How has this issue affected you? What are you trying to accomplish?
**Providing context helps us come up with a solution that is most useful in the real world**

---
Please include a copy of any relevant log output to assist in tracking down the [4/10/2021, 1:45:16 AM] ====================
[4/10/2021, 1:45:16 AM] ERROR LOADING PLUGIN homebridge-smartthings-v2:
[4/10/2021, 1:45:16 AM] Error: Cannot find module '/usr/local/lib/node_modules/homebridge-smartthings-v2/index.js'
Require stack:
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/src/plugin.ts:187:27)
    at /usr/local/lib/node_modules/homebridge/src/pluginManager.ts:126:16
    at Map.forEach (<anonymous>)
    at PluginManager.initializeInstalledPlugins (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:124:18)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:156:24)
[4/10/2021, 1:45:16 AM] ====================

**Comment by BUMPRW** [comment]
I checked index.js isn't there

**Comment by HonbraDev** [comment]
Same, to fix the problem, just edit the `main` property in `package.json` from `index.js` to `src/index.js`.
